# google project id: unior4nlp
# url: https://unior4nlp.appspot.com
# deploy test/production

runtime: python37

# uncommenting this cause problesm (not clear why)
# instance_class: B1
# basic_scaling:
#   max_instances: 2
#   idle_timeout: 10m